<?php
return [
    'name' => 'Mscons Segment Beschreibung',

    'amount_type' => [
        '220' => 'Wahrer Wert',
        '67' => 'Ersatzwert',
        'Z18' => 'Vorläufiger Wert',
    ],

    'audit_note' => [
        'Z83' => 'Kundenselbstablesung',
        'Z84' => 'Leerstand',
        'Z85' => 'Realer Zählerüberlauf geprüft',
        'Z86' => 'Plausibel wg. Kontrollablesung',
        'Z87' => 'Plausibel wg. Kundenhinweis',
        'ZC3' => 'Austausch des Ersatzwertes',
        'ZR5' => 'Rechenwert',
        'ZS2' => 'Wert auf Basis der modernen Messeinrichtung',
    ],
    'estimation_method' => [
        'Z88' => 'Vergleichsmessung (geeicht)',
        'Z89' => 'Vergleichsmessung nicht (geeicht)',
        'Z90' => 'Messwertnachbildung aus geeichten Werten',
        'Z91' => 'Messwertnachbildung aus nicht geeichten Werten',
        'Z92' => 'Interpolation',
        'Z93' => 'Haltewert',
        'Z94' => 'Bilanzierung Netzabschnitt',
        'Z95' => 'Historische Messwerte',
        'Z89' => 'Vergleichsmessung nicht (geeicht)',
        'Z92' => 'Interpolation',
        'ZJ2' => 'Statistische Methode',
        'ZQ8' => 'Aufteilung',
        'ZQ9' => 'Verwendung von Werten des Störmengenzählwerks',
        'ZR0' => 'Umgangs- und Korrekturmengen',
        'ZS0' => 'Ersatzwertbildungsverfahren gemäß Angaben auf Ebene der Messlokation',
    ],
    'altering_reason' => [
        'Z74' => 'kein Zugang',
        'Z75' => 'Kommunikationsstörung',
        'Z76' => 'Kommunikationsstörung',
        'Z77' => 'Spannungsausfall',
        'Z78' => 'Gerätewechsel',
        'Z79' => 'Kalibrierung',
        'Z80' => 'Gerät arbeitet außerhalb der Betriebsbedingungen',
        'Z81' => 'Messeinrichtung gestört/ defekt',
        'Z82' => 'Unsicherheit Messung',
        'Z98' => 'Berücksichtigung Störmengenzählwerk',
        'Z99' => 'Mengenumwertung unvollständig',
        'ZA0' => 'Uhrzeit gestellt / Synchronisation',
        'ZA1' => 'Messwert unplausibel',
        'ZA3' => 'Falscher Wandlerfaktor',
        'ZA4' => 'Fehlerhafte Ablesung',
        'ZA5' => 'Änderung der Berechnung',
        'ZA6' => '6 Umbau der Messlokation',
        'ZA7' => '7 Datenbearbeitungsfehler',
        'ZA8' => 'Brennwertkorrektur',
        'ZA9' => '9 Z-Zahl-Korrektur',
        'ZB0' => 'Störung / Defekt Messeinrichtung',
        'ZB9' => 'Änderung Tarifschaltzeiten',
        'ZC2' => 'Tarifschaltgerät defekt',
        'ZC4' => 'Impulswertigkeit nicht ausreichend',
        'ZJ9' => 'Energiemenge aus dem ungepairten Zeitintervall ',
        'ZR1' => 'Wartungsarbeiten an geeichtem Messgerät',
        'ZR2' => 'gestörte Werte',
        'ZR3' => 'Wartungsarbeiten an eichrechtskonformen Messgeräten',
        'ZR4' => 'Konsistenz- und Synchronprüfung',
    ],
    'estimation_reason' => [
        'Z74' => 'kein Zugang',
        'Z75' => 'Kommunikationsstörung',
        'Z76' => 'Kommunikationsstörung',
        'Z77' => 'Spannungsausfall',
        'Z78' => 'Gerätewechsel',
        'Z79' => 'Kalibrierung',
        'Z80' => 'Gerät arbeitet außerhalb der Betriebsbedingungen',
        'Z81' => 'Messeinrichtung gestört/ defekt',
        'Z82' => 'Unsicherheit Messung',
        'Z98' => 'Berücksichtigung Störmengenzählwerk',
        'Z99' => 'Mengenumwertung unvollständig',
        'ZA0' => 'Uhrzeit gestellt / Synchronisation',
        'ZA1' => 'Messwert unplausibel',
        'ZA3' => 'Falscher Wandlerfaktor',
        'ZA4' => 'Fehlerhafte Ablesung',
        'ZA5' => 'Änderung der Berechnung',
        'ZA6' => '6 Umbau der Messlokation',
        'ZA7' => '7 Datenbearbeitungsfehler',
        'ZB0' => 'Störung / Defekt Messeinrichtung',
        'ZB9' => 'Änderung Tarifschaltzeiten',
        'ZC2' => 'Tarifschaltgerät defekt',
        'ZC4' => 'Impulswertigkeit nicht ausreichend',
        'ZR1' => 'Wartungsarbeiten an geeichtem Messgerät',
        'ZR2' => 'gestörte Werte',
        'ZR3' => 'Wartungsarbeiten an eichrechtskonformen Messgeräten',
        'ZR4' => 'Konsistenz- und Synchronprüfung',
        'ZS9' => 'Grund der Ersatzwertbildung gemäß Angaben auf Ebene der Messlokation',
    ],
];
