<?php

return [
    'E_0007' => [
        'A01' => 'Fristüberschreitung',
        'A02' => 'Gewählter Zeitpunkt nicht zulässig',
        'A03' => 'Zeitreihe bereits vorhanden',
        'A04' => 'Version nicht zugelassen',
        'A05' => 'Energiemenge falsch / nicht plausibel',
    ],
    'E_0020' => [
        'A01' => 'Fristüberschreitung',
        'A02' => 'Gewählter Zeitpunkt nicht zulässig',
        'A03' => 'ID bereits außerhalb MaBiS verwendet',
        'A04' => 'Bilanzierungsgebiet des benachbarten NB nicht gültig',
        'A05' => 'Regelzone falsch',
        'A06' => 'Keine Berechtigung',
        'A07' => 'Abweichender MaBiS-ZP bereits vorhanden',
        'A08' => 'Abweichende ID zum MaBiS-ZP bereits vorhanden',
        'A09' => 'ZRT Aktivierung nicht berechtigt',
        'A10' => 'OBIS nicht passend',
        'A11' => 'MaBiS-ZP bereits aktiviert',
    ],
    'E_0021' => [
        'A01' => 'Fristüberschreitung',
        'A02' => 'Gewählter Zeitpunkt nicht zulässig',
        'A03' => 'Bilanzierungsgebiet des verantwortlichen NB nicht gültig',
        'A04' => 'Bilanzierungsgebiet des benachbarten NB nicht gültig',
        'A05' => 'Regelzone falsch',
        'A06' => 'Keine Berechtigung',
        'A07' => 'Abweichender MaBiS-ZP bereits vorhanden',
        'A08' => 'Abweichende ID zum MaBiS-ZP bereits vorhanden',
        'A09' => 'ZRT Aktivierung nicht berechtigt',
        'A10' => 'OBIS nicht passend',
        'A11' => 'MaBiS-ZP bereits aktiviert',
    ],
    'E_0046' => [
        'A01' => 'Zeitraum nicht plausibel',
        'A02' => 'MaBiS-ZP entspricht nicht dem angefragten MaBiSZP',
        'A03' => 'Version nicht zugelassen',
        'A04' => 'Zusätzlicher Datensatz / ergänzte Marktlokation',
        'A05' => 'Marktlokation falschem LF zugeordnet',
        'A06' => 'Zu viele Marktlokationen enthalten / entfallene Marktlokation',
        'A07' => 'Bilanzierungsrel. Daten nicht korrekt / fehlen',
    ],
    'E_0049' => [
        'A01' => 'Abonnement wurde nicht bestellt',
        'A02' => 'Version nicht zugelassen',
        'A03' => 'Zusätzlicher Datensatz / ergänzte Marktlokation',
        'A04' => 'Marktlokation falschem LF zugeordnet',
        'A05' => 'Zu viele Marktlokationen enthalten / entfallene Marktlokation',
        'A06' => 'Bilanzierungsrel. Daten nicht korrekt / fehlen',
    ],
    'E_0400' => [
        'A12' => 'Fristüberschreitung',
        'A01' => 'Die Marktlokation ist nicht identifizierbar',
        'A02' => 'Angefragter Kunde ist nicht der Vertragspartner beim LFA',
        'A03' => 'Keine Identifizierung einer Marktlokation',
        'A04' => 'Mehrere Marktlokationen wurden identifiziert, Kunde war bei keiner bzw. mehreren Marktlokationen zugeordnet',
        'A05' => 'Teil einer Kundenanlage, die derzeit nicht separat bilanziert wird',
        'A13' => 'Empfänger ist zum angefragten Zeitpunkt nicht zugeordnet',
        'A07' => 'Zum Kündigungstermin besteht kein Vertragsverhältnis mehr',
        'A08' => 'Vertragsbindung bei bereits in der Zukunft beendetem Vertrag',
        'A09' => 'Vertragsbindung',
        'A99' => 'Sonstiges',
    ],
    'E_0462' => [
        'A01' => 'Marktlokation ist nicht identifizierbar',
        'A02' => 'Mehrfachidentifizierung',
        'A03' => 'Keine Identifizierung',
        'A04' => 'Marktlokation befindet sich zum Eingangsdatum der Meldung nicht mehr im Netzgebiet des NB',
        'A13' => 'Es handelt sich nicht um einen Einzug, da zum genannten Datum kein Anschlussnutzerwechsel stattfand',
        'A05' => 'Eingangsfrist bei iMS / kME mit RLM nicht eingehalten',
        'A06' => 'Fristüberschreitung bei kME ohne RLM / mME / Pauschalanlage',
        'A09' => 'Frist bei einem Lieferantenwechsel nicht eingehalten im Rahmen der schnellen Identifikation',
        'A10' => 'Frist bei einem Lieferantenwechsel nicht eingehalten im Rahmen der langsamen Identifikation',
        'A11' => 'Andere Anmeldung in Bearbeitung',
        'A12' => 'Zuordnungsermächtigung fehlt',
        'A14' => 'Grundversorger ist der Marktlokation nicht zugeordnet',
    ],
    'E_0403' => [
        'A30' => 'Die Belieferung wurde zu dem angefragten Termin aus der Abmeldeanfrage bereits beendet und eine Abmeldung von dem LFA bereits versendet, die durch den NB bereits bestätigt wurde',
        'A32' => 'Es handelt sich nicht um einen Einzug, da der Kunde aus der Abmeldeanfrage identisch mit dem Kunden beim LFA ist',
        'A33' => 'Der LFA hat die Information, dass der Kunde nicht ausgezogen ist',
        'A35' => 'Es besteht eine Vertragsbindung',
        'A37' => 'Die Marktlokation befindet sich nicht in der Ersatzversorgung',
        'A04' => 'Marktlokation befindet sich zum Eingangsdatum der Meldung nicht mehr im Netzgebiet des NB',
        'A04' => 'Marktlokation befindet sich zum Eingangsdatum der Meldung nicht mehr im Netzgebiet des NB',
        'A04' => 'Marktlokation befindet sich zum Eingangsdatum der Meldung nicht mehr im Netzgebiet des NB',
    ],
    'E_0404' => [
        'A50' => 'Der LFA hat der Abmeldeanfrage widersprochen',
        'A99' => 'Sonstiges',
    ],
    'E_0439' => [
        'A01' => 'Bilanzierungsproblem',
        'A02' => 'Nicht alle Messlokationen der Marktlokation mit iMS ausgestattet',
        'A03' => 'Kein Wahlrecht des Bilanzierungsverfahrens für die Marktlokation',
        'A04' => 'Änderung zum gewünschten Termin bereits umgesetzt.',
        'A05' => 'Fristüberschreitung',
    ],
    'E_0440' => [
        'A02' => 'Fristüberschreitung',
        'A03' => 'Kein stabiler Verbindungsaufbau zur Konfiguration
des iMS',
    ],
    'E_0441' => [
        'A01' => 'Keine Berechtigung',
    ],
    'E_0442' => [
        'A01' => 'Falscher Prozess',
        'A02' => 'Keine Berechtigung',
        'A03' => 'Es wurden Werte angefragt, die es auf der genannten Marktlokation, Messlokation oder Tranche nicht geben kann.',
        'A04' => 'Die angefragten Werte sind nicht vorhanden',
    ],
    'E_0456' => [
        'A01' => 'Für diese Marktlokation ist kein Lieferschein zu versenden',
        'A02' => 'Endedatum liegt in der Zukunft',
        'A03' => 'Der Typ des Lieferscheins ist nicht identisch zur Netznutzungsabrechnungsvariante',
        'A04' => 'Überschneidender Zeitraum in noch nicht stornierten Lieferscheinen „Arbeitspreis/Grundpreis“',
        'A06' => 'Energiemenge für pauschale Marktlokation stimmt nicht überein',
        'A07' => 'Energiemengen vom MSB an der Marktlokation fehlen und sind beim MSB reklamiert',
        'A08' => 'Für einen Zeitabschnitt liegen für mindestens eine OBIS-Kennzahl mehrere Energiemengen vor',
        'A09' => 'Energiemenge widerspricht vertraglich vereinbarter Logik',
        'A10' => 'Energiemengen stimmen nicht überein',
        'A11' => 'Energiemenge für pauschale Marktlokation stimmt nicht überein',
        'A12' => 'Lastgänge vom MSB an der Marktlokation fehlen und sind beim MSB reklamiert oder das Arbeitsund Leistungsmaximum Kalenderjahr vor Lieferbeginn vom NB fehlt',
        'A13' => 'Energiemenge bzw. Leistungsmaximum aus dem Lieferschein entspricht nicht der vertraglich vereinbarten Energiemenge',
        'A14' => 'Leistungsmaximum aus dem Lieferschein ist nicht identisch zum vorliegenden Leistungsmaximum',
        'A15' => 'Leistungsmaximum unplausibel',
        'A16' => 'Energiemenge aus dem Lieferschein entspricht nicht der Summe aus dem Lastgang',
    ],
    'E_0456' => [
        'A01' => 'Für diese Marktlokation ist kein Lieferschein zu versenden',
    ],
    'E_0453' => [
        'A01' => 'Regelzone falsch',
        'A02' => 'Netzbetreiber nicht gültig',
        'A03' => 'Bilanzierungsgebiet nicht gültig',
        'A14' => 'Angegebener NB entspricht nicht dem zugeordneten NB des Bilanzierungsgebiets',
        'A15' => 'Messstellenbetreiber nicht gültig',
        'A04' => 'LF im Vorgang weicht vom Absender ab',
        'A05' => 'Bilanzkreis nicht gültig',
        'A16' => 'Prognosegrundlage passt nicht zum ZRT',
        'A06' => 'OBIS nicht passend',
        'A07' => 'Lieferrichtung nicht passend',
        'A17' => 'Aggregationsverantwortlicher im Vorgang passt nicht zur Aggregationsverantwortung der Marktlokation im System des ÜNB',
        'A18' => 'Falscher Aggregationsverantwortlicher',
        'A08' => 'ZRT nicht passend',
        'A09' => 'Bilanzierungsverfahren nicht gültig',
        'A10' => 'Normiertes Profil liegt nicht vor',
        'A11' => 'Normiertes Profil nicht SLP mit synthetischem Verfahren',
        'A12' => 'Unpassende Prognosegrundlage',
        'A99' => 'Ablehnung Sonstiges',
    ],
    'E_0455' => [
        'A01' => 'Zuordnung der Datenaggregation liegt bereits vor',
        'A02' => 'Regelzone falsch',
        'A03' => 'Netzbetreiber nicht gültig',
        'A04' => 'Bilanzierungsgebiet nicht gültig',
        'A16' => 'Angegebener Netzbetreiber entspricht nicht dem zugeordneten Netzbetreiber des Bilanzierungsgebiets',
        'A18' => 'Messstellenbetreiber nicht gültig',
        'A05' => 'LF im Vorgang weicht vom Absender ab.',
        'A06' => 'Bilanzkreis nicht gültig',
        'A07' => 'ZRT nicht passend',
        'A17' => 'Prognosegrundlage passt nicht zum ZRT.',
        'A08' => 'OBIS nicht passend',
        'A09' => 'Lieferrichtung nicht passend',
        'A10' => 'Bilanzierungsverfahren nicht gültig',
        'A11' => 'Falscher Aggregationsverantwortlicher',
        'A12' => 'Normiertes Profil liegt nicht vor',
        'A13' => 'Normiertes Profil – nicht SLP mit synthetischem Verfahren',
        'A14' => 'Unpassende Prognosegrundlage',
        'A99' => 'Ablehnung Sonstiges',
    ],
    'S_0004' => [
        'E14' => 'Ablehnung Sonstiges',
        'E17' => 'Ablehnung wg. Fristüberschreitung',
        'Z08' => 'Ablehnung (Transaktion schon stattgefunden)',
        'Z09' => 'Ablehnung (Transaktionsgrund unplausibel)',
        'Z14' => 'Ablehnung (Doppelmeldung)',
        'Z30' => 'Ablehnung (kein Grund-/Ersatzversorgungsfall)',
        'ZI3' => 'Ablehnung Die Energiemenge für eine Strom SLP/TLP Marktlokation wurde > 200.000 kWh angegeben',
        'ZI5' => 'Ablehnung Die spezifische Arbeit für eine TLP Marktlokation wurde > 80 kWh/K angegeben',
        'ZI7' => 'Ablehnung Die Energiemenge für eine Pauschalanlage wurde > 200.000 kWh angegeben',
    ],
    'S_0007' => [
        'E17' => 'Ablehnung wg. Fristüberschreitung',
        'ZF9' => 'Ablehnung Prognosegrundlage entspricht nicht der Ausgetauschten',
        'ZI3' => 'Ablehnung Die Energiemenge für eine Strom SLP/TLP Marktlokation wurde > 200.000 kWh angegeben',
        'ZI5' => 'Ablehnung Die spezifische Arbeit für eine TLP Marktlokation wurde > 80 kWh/K angegeben',
        'ZI7' => 'Ablehnung Die Energiemenge für eine Pauschalanlage wurde > 200.000 kWh angegebe',
    ],
    'S_0008' => [
        'E17' => 'Ablehnung wg. Fristüberschreitung',
        'ZF9' => 'Ablehnung – Prognosegrundlage entspricht nicht der Ausgetauschten',
        'ZI3' => 'Ablehnung – Die Energiemenge für eine Strom SLP/TLP Marktlokation wurde > 200.000 kWh angegeben',
        'ZI5' => 'Ablehnung – Die spezifische Arbeit für eine TLP Marktlokation wurde > 80 kWh/K angegeben',
        'ZI7' => 'Ablehnung – Die Energiemenge für eine Pauschalanlage wurde > 200.000 kWh angegeben',
    ],
    'S_0009' => [
        'E17' => 'Ablehnung wg. Fristüberschreitung',
        'ZI3' => 'Ablehnung Die Energiemenge für eine Strom SLP/TLP Marktlokation wurde > 200.000 kWh angegeben',
        'ZI5' => 'Ablehnung Die spezifische Arbeit für eine TLP Marktlokation wurde > 80 kWh/K angegeben',
        'ZI7' => 'Ablehnung Die Energiemenge für eine Pauschalanlage wurde > 200.000 kWh angegeben',
    ],
    'S_0010' => [
        'E17' => 'Ablehnung wg. Fristüberschreitung',
        'ZI3' => 'Ablehnung – Die Energiemenge für eine Strom SLP/TLP Marktlokation wurde > 200.000 kWh angegeben',
        'ZI5' => 'Ablehnung – Die spezifische Arbeit für eine TLP Marktlokation wurde > 80 kWh/K angegeben',
        'ZI7' => 'Ablehnung – Die Energiemenge für eine Pauschalanlage wurde > 200.000 kWh angegeben',
    ],
    'S_0013' => [
        'ZJ5' => 'Lieferrichtung steht im Widerspruch zur gemeldeten Marktlokation',
    ],
    'S_0017' => [
        'E13' => 'Ablehnung (Bilanzierungsproblem)',
        'E17' => 'Ablehnung wg. Fristüberschreitung',
    ],
    'S_0021' => [
        'ZG0' => 'Ablehnung Stammdaten an der Markt- bzw. Messlokation nicht vorhanden',
    ],
    'S_0022' => [
        'ZG0' => 'Ablehnung Stammdaten an der Markt- bzw. Messlokation nicht vorhanden',
    ],
    'S_0023' => [
        'ZG4' => 'Frist nicht eingehalten, Übermittlung Datenstand',
    ],
    'S_0024' => [
        'ZG4' => 'Frist nicht eingehalten, Übermittlung Datenstand',
    ],
    'S_0025' => [
        'ZG4' => 'Frist nicht eingehalten, Übermittlung Datenstand',
    ],
    'S_0026' => [
        'ZG4' => 'Frist nicht eingehalten, Übermittlung Datenstand',
    ],
    'S_0027' => [
        'ZJ5' => 'Lieferrichtung steht im Widerspruch zur gemeldeten Marktlokation',
    ],
    'S_0030' => [
        'ZG0' => 'Ablehnung Stammdaten an der Markt- bzw. Messlokation nicht vorhanden',
    ],
    'S_0031' => [
        'ZG0' => 'Ablehnung Stammdaten an der Markt- bzw. Messlokation nicht vorhanden',
    ],
    'S_0032' => [
        'ZG4' => 'Frist nicht eingehalten, Übermittlung Datenstand',
    ],
    'S_0033' => [
        'ZG0' => 'Ablehnung Stammdaten an der Markt- bzw. Messlokation nicht vorhanden',
    ],
    'S_0035' => [
        'ZD3' => 'Ablehnung – Verantwortlicher hat nicht geantwortet',
        'ZG0' => 'Ablehnung Stammdaten an der Markt- bzw. Messlokation nicht vorhanden',
    ],
    'S_0037' => [
        'ZD3' => 'Ablehnung – Verantwortlicher hat nicht geantwortet',
    ],
    'S_0094' => [
        'ZG0' => 'Ablehnung Stammdaten an der Markt- bzw. Messlokation nicht vorhanden',
    ],
    'S_0081' => [
        'E14' => 'Ablehnung Sonstiges',
        'E17' => 'Ablehnung wg. Fristüberschreitung',
        'Z08' => 'Ablehnung (Transaktion schon stattgefunden)',
        'Z14' => 'Ablehnung (Doppelmeldung)',
        'E17' => 'Ablehnung wg. Fristüberschreitung',
        'E17' => 'Ablehnung wg. Fristüberschreitung',
    ],
    'S_0083' => [
        'E13' => 'Ablehnung (Bilanzierungsproblem)',
        'E14' => 'Ablehnung Sonstiges',
        'E17' => 'Ablehnung wg. Fristüberschreitung',
        'Z08' => 'Ablehnung (Transaktion schon stattgefunden)',
        'Z09' => 'Ablehnung (Transaktionsgrund unplausibel)',
        'Z14' => 'Ablehnung (Doppelmeldung)',
    ],
    'S_0087' => [
        'E14' => 'Ablehnung Sonstiges',
        'Z14' => 'Ablehnung (Doppelmeldung)',
        'ZE1' => 'Ablehnung – zu stornierender Vorgang wurde schon beantwortet',
    ],
    'S_0098' => [
        'ZG0' => 'Ablehnung Stammdaten an der Markt- bzw. Messlokation nicht vorhanden',
        'ZD3' => 'Ablehnung – Verantwortlicher hat nicht geantwortet',
    ],
    'S_0100' => [
        'ZG0' => 'Ablehnung Stammdaten an der Markt- bzw. Messlokation nicht vorhanden',
        'ZD3' => 'Ablehnung – Verantwortlicher hat nicht geantwortet',
    ],
    'S_0102' => [
        'ZD3' => 'Ablehnung – Verantwortlicher hat nicht geantwortet',
    ],
    'G_0002' => [
        'ZE0' => 'Ablehnung – Stammdaten richtig',
    ],
    'G_0003' => [
        'E14' => 'Ablehnung Sonstiges',
        'Z14' => 'Ablehnung (Doppelmeldung)',
        'ZE1' => 'Ablehnung – zu stornierender Vorgang wurde schon beantwortet',
    ],
    'G_0005' => [
        'E14' => 'Ablehnung Sonstiges',
        'Z12' => 'Ablehnung Vertragsbindung',
        'Z29' => 'Ablehnung (kein Vertragsverhältnis mehr vorhanden)',
        'Z34' => 'Ablehnung (Mehrfachkündigung)',
        'A03' => 'Ablehnung (Keine Identifizierung einer Marktlokation)',
        'A04' => 'Ablehnung (Mehrere Marktlokationen wurden identifiziert, Kunde war bei keiner bzw. mehreren Marktlokationen zugeordnet.)',
    ],
    'G_0007' => [
        'E14' => 'Ablehnung Sonstiges',
        'E17' => 'Ablehnung wg. Fristüberschreitung',
        'Z08' => 'Ablehnung (Transaktion schon stattgefunden)',
        'Z14' => 'Ablehnung (Doppelmeldung)',
    ],
    'G_0009' => [
        'E14' => 'Ablehnung Sonstiges',
        'Z08' => 'Ablehnung (Transaktion schon stattgefunden)',
        'Z09' => 'Ablehnung (Transaktionsgrund unplausibel)',
        'Z12' => 'Ablehnung Vertragsbindung',
        'Z14' => 'Ablehnung (Doppelmeldung)',
    ],
    'G_0011' => [
        'E13' => 'Ablehnung (Bilanzierungsproblem)',
        'E14' => 'Ablehnung Sonstiges',
        'E17' => 'Ablehnung wg. Fristüberschreitung',
        'Z08' => 'Ablehnung (Transaktion schon stattgefunden)',
        'Z09' => 'Ablehnung (Transaktionsgrund unplausibel)',
        'Z14' => 'Ablehnung (Doppelmeldung)',
        'Z35' => 'Ablehnung der Abmeldeanfrage',
        'ZC5' => 'Ablehnung (andere Anmeldung in Bearbeitung)',
        'ZE2' => 'Ablehnung Kapazitätsproblem',
        'A02' => 'Ablehnung (Mehrfachidentifizierung)',
        'A03' => 'Ablehnung (Keine Identifizierung einer Marktlokation)',
        'A04' => 'Ablehnung (Mehrere Marktlokationen wurden identifiziert, Kunde war bei keiner bzw. mehreren Marktlokationen zugeordnet.)',
    ],
    'G_0014' => [
        'E14' => 'Ablehnung Sonstiges',
        'E17' => 'Ablehnung wg. Fristüberschreitung',
        'Z08' => 'Ablehnung (Transaktion schon stattgefunden)',
        'Z09' => 'Ablehnung (Transaktionsgrund unplausibel)',
        'Z14' => 'Ablehnung (Doppelmeldung)',
        'Z30' => 'Ablehnung (kein Grund-/Ersatzversorgungsfall)',
        'ZI4' => 'Ablehnung Die Energiemenge für eine Gas SLP Marktlokation wurde > 2.250.000 kWh angegeben',
        'ZI6' => 'Ablehnung Der Kundenwert nach TUM wurde > 6.200 kWh angegeben',
        'ZI7' => 'Ablehnung Die Energiemenge für eine Pauschalanlage wurde > 200.000 kWh angegeben',
    ],
    'G_0018' => [
        'E17' => 'Ablehnung wg. Fristüberschreitung',
        'ZF9' => 'Ablehnung Prognosegrundlage entspricht nicht der Ausgetauschten',
        'ZI4' => 'Ablehnung Die Energiemenge für eine Gas SLP Marktlokation wurde > 2.250.000 kWh angegeben',
        'ZI6' => 'Ablehnung Der Kundenwert nach TUM wurde > 6.200 kWh angegeben',
        'ZI7' => 'Ablehnung Die Energiemenge für eine Pauschalanlage wurde > 200.000 kWh angegeben',
    ],
    'G_0019' => [
        'E17' => 'Ablehnung wg. Fristüberschreitung',
        'ZI4' => 'Ablehnung Die Energiemenge für eine Gas SLP Marktlokation wurde > 2.250.000 kWh angegeben',
        'ZI6' => 'Ablehnung Der Kundenwert nach TUM wurde > 6.200 kWh angegeben',
        'ZI7' => 'Ablehnung Die Energiemenge für eine Pauschalanlage wurde > 200.000 kWh angegeben',
    ],
    'G_0022' => [
        'ZJ5' => 'Lieferrichtung steht im Widerspruch zur gemeldeten Marktlokation',
    ],
    'G_0023' => [
        'E13' => 'Ablehnung (Bilanzierungsproblem)',
        'E17' => 'Ablehnung wg. Fristüberschreitung',
        'ZE2' => 'Ablehnung Kapazitätsproblem',
    ],
    'G_0025' => [
        'E13' => 'Ablehnung (Bilanzierungsproblem)',
        'E17' => 'Ablehnung wg. Fristüberschreitung',
        'ZE2' => 'Ablehnung Kapazitätsproblem',
    ],
    'G_0031' => [
        'ZG0' => 'Ablehnung Stammdaten an der Markt- bzw. Messlokation nicht vorhanden',
    ],
    'G_0032' => [
        'ZG4' => 'Frist nicht eingehalten, Übermittlung Datenstand',
    ],
    'G_0033' => [
        'ZG0' => 'Ablehnung Stammdaten an der Markt- bzw. Messlokation nicht vorhanden',
    ],
    'G_0034' => [
        'ZG4' => 'Frist nicht eingehalten, Übermittlung Datenstand',
    ],
    'G_0036' => [
        'ZJ5' => 'Lieferrichtung steht im Widerspruch zur gemeldeten Marktlokation',
    ],
    'G_0038' => [
        'ZG4' => 'Frist nicht eingehalten, Übermittlung Datenstand',
    ],
    'G_0039' => [
        'ZG0' => 'Ablehnung Stammdaten an der Markt- bzw. Messlokation nicht vorhanden',
    ],
    'G_0040' => [
        'ZG0' => 'Ablehnung Stammdaten an der Markt- bzw. Messlokation nicht vorhanden',
    ],
    'G_0042' => [
        'ZD3' => 'Ablehnung Verantwortlicher hat nicht geantwortet',
        'ZG0' => 'Ablehnung Stammdaten an der Markt- bzw. Messlokation nicht vorhanden',
    ],
    'G_0043' => [
        'ZG0' => 'Ablehnung Stammdaten an der Markt- bzw. Messlokation nicht vorhanden',
    ],
    'G_0046' => [
        'ZD3' => 'Ablehnung Verantwortlicher hat nicht geantwortet',
        'ZG0' => 'Ablehnung Stammdaten an der Markt- bzw. Messlokation nicht vorhanden',
    ],
    'G_0048' => [
        'ZD3' => 'Ablehnung Verantwortlicher hat nicht geantwortet',
    ],
    'G_0049' => [
        'Z15' => 'Ablehnung keine Berechtigung',
    ],
    'G_0050' => [
        'Z15' => 'Ablehnung keine Berechtigung',
        'Z21' => 'Ablehnung Daten nicht vorhanden',
    ],
    'G_0068' => [
        'E13' => 'Ablehnung (Bilanzierungsproblem)',
        'E14' => 'Ablehnung Sonstiges',
        'E17' => 'Ablehnung wg. Fristüberschreitung',
        'Z08' => 'Ablehnung (Transaktion schon stattgefunden)',
        'Z09' => 'Ablehnung (Transaktionsgrund unplausibel)',
        'Z14' => 'Ablehnung (Doppelmeldung)',
    ],
    'G_0069' => [
        'ZG0' => 'Ablehnung Stammdaten an der Markt- bzw. Messlokation nicht vorhanden',
    ],
    'G_0078' => [
        'Z15' => 'Ablehnung keine Berechtigung',
    ],
    'GS_001' => [
        'E13' => 'Ablehnung (Bilanzierungsproblem)',
        'E17' => 'Ablehnung wg. Fristüberschreitung',
    ],
];
