<?php
return [
    'E09' => 'Ablehnung (Lieferadresse nicht im Verteilnetz)',
    'E10' => 'Ablehnung (Lieferadresse nicht identifizierbar)',
    'E11' => 'Ablehnung (Messproblem)',
    'E12' => 'Ablehnung (unklares Lieferverhältnis)',
    'E13' => 'Ablehnung (Bilanzierungsproblem)',
    'E14' => 'Ablehnung (Sonstiges)',
    'E17' => 'Ablehnung (Fristüberschreitung)',
    'Z05' => 'Empfänger-MP-ID und Empfänger stimmen nicht überein',
    'Z06' => 'Ablehnung (Kunde nicht identifizierbar)',
    'Z07' => 'Ablehnung (Keine Berechtigung)',
    'Z08' => 'Ablehnung (Transaktion schon stattgefunden)',
    'Z09' => 'Ablehnung (Transaktion unplausibel)',
    'Z10' => 'Ablehnung (Abmeldung fehlt)',
    'Z11' => 'Ablehnung (Termin fehlt)',
    'Z12' => 'Ablehnung (Vertragsbindung)',
    'Z13' => 'Ablehnung (Meldung nicht identifizierbar)',
    'Z14' => 'Ablehnung (Doppeltmeldung)',
    'Z29' => 'Ablehnung (kein Vertragsverhältnis)',
    'Z34' => 'Ablehnung (Mehrfachkündigung)',
    'Z35' => 'Ablehnung der Abmeldungsanfrage.',
    'Z47' => 'Änderungsmitteilung von bilanzierungsrel. Daten',
    'ZC5' => 'Ablehnung (andere Anmeldung in Bearbeitung)',
    'ZD5' => 'Ablehnung untermonatlicher Wechseltermin',
    'ZD6' => 'Ablehnung unplausible Dateninhalte',
    'ZE0' => 'Ablehnung Stammdaten richtig',
    'ZE1' => 'Ablehnung zu stornierender Vorgang wurde schon beantwortet',
    'ZE2' => 'Ablehnung Kapazitätsprobleme',
];
